In [1]:
import pandas as pd
import requests

In [2]:
resp = requests.get("https://restcountries.eu/rest/v2/all")
df = pd.DataFrame(resp.json())

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 24 columns):
alpha2Code        250 non-null object
alpha3Code        250 non-null object
altSpellings      250 non-null object
area              240 non-null float64
borders           250 non-null object
callingCodes      250 non-null object
capital           250 non-null object
cioc              247 non-null object
currencies        250 non-null object
demonym           250 non-null object
flag              250 non-null object
gini              153 non-null float64
languages         250 non-null object
latlng            250 non-null object
name              250 non-null object
nativeName        250 non-null object
numericCode       249 non-null object
population        250 non-null int64
region            250 non-null object
regionalBlocs     250 non-null object
subregion         250 non-null object
timezones         250 non-null object
topLevelDomain    250 non-null object
translations      250 non-null object
dtypes: float64(2), int64(1), object(21)
memory usage: 47.0+ KB

In [8]:
df.loc[df.population < 100000, ['name','population']]

name          50
population    50
dtype: int64

In [9]:
df.head()

,alpha2Code,alpha3Code,altSpellings,area,borders,callingCodes,capital,cioc,currencies,demonym,...,name,nativeName,numericCode,population,region,regionalBlocs,subregion,timezones,topLevelDomain,translations
0,AF,AFG,"[AF, Afġānistān]",652230.0,"[IRN, PAK, TKM, UZB, TJK, CHN]",[93],Kabul,AFG,"[{'code': 'AFN', 'name': 'Afghan afghani', 'sy...",Afghan,...,Afghanistan,افغانستان,004,27657145,Asia,"[{'acronym': 'SAARC', 'name': 'South Asian Ass...",Southern Asia,[UTC+04:30],[.af],"{'de': 'Afghanistan', 'es': 'Afganistán', 'fr'..."
1,AX,ALA,"[AX, Aaland, Aland, Ahvenanmaa]",1580.0,[],[358],Mariehamn,,"[{'code': 'EUR', 'name': 'Euro', 'symbol': '€'}]",Ålandish,...,Åland Islands,Åland,248,28875,Europe,"[{'acronym': 'EU', 'name': 'European Union', '...",Northern Europe,[UTC+02:00],[.ax],"{'de': 'Åland', 'es': 'Alandia', 'fr': 'Åland'..."
2,AL,ALB,"[AL, Shqipëri, Shqipëria, Shqipnia]",28748.0,"[MNE, GRC, MKD, KOS]",[355],Tirana,ALB,"[{'code': 'ALL', 'name': 'Albanian lek', 'symb...",Albanian,...,Albania,Shqipëria,008,2886026,Europe,"[{'acronym': 'CEFTA', 'name': 'Central Europea...",Southern Europe,[UTC+01:00],[.al],"{'de': 'Albanien', 'es': 'Albania', 'fr': 'Alb..."
3,DZ,DZA,"[DZ, Dzayer, Algérie]",2381741.0,"[TUN, LBY, NER, ESH, MRT, MLI, MAR]",[213],Algiers,ALG,"[{'code': 'DZD', 'name': 'Algerian dinar', 'sy...",Algerian,...,Algeria,الجزائر,012,40400000,Africa,"[{'acronym': 'AU', 'name': 'African Union', 'o...",Northern Africa,[UTC+01:00],[.dz],"{'de': 'Algerien', 'es': 'Argelia', 'fr': 'Alg..."
4,AS,ASM,"[AS, Amerika Sāmoa, Amelika Sāmoa, Sāmoa Amelika]",199.0,[],[1684],Pago Pago,ASA,"[{'code': 'USD', 'name': 'United State Dollar'...",American Samoan,...,American Samoa,American Samoa,016,57100,Oceania,[],Polynesia,[UTC-11:00],[.as],"{'de': 'Amerikanisch-Samoa', 'es': 'Samoa Amer..."